export const english: Record<string, string> = {
"到期提醒":"Expiry reminders",
"搜索节点…":"Search nodes…",
"匹配节点":"Matching nodes",
"当前查看范围":"Current view range",
"刚刚":"Just now",
"{0} 分钟前":"{0} minutes ago",
"{0} 小时前":"{0} hours ago",
"{0} 天前":"{0} days ago",
"紧凑显示关键状态；详细显示流量、在线时长和连接数。":"Compact shows key status; detailed adds traffic, uptime and connections.",
"仅控制内存和硬盘的容量说明。":"Controls memory and disk capacity details only.",
"保存在此浏览器，影响新打开的历史图表。":"Saved in this browser for newly opened history charts.",
"仅重置列表显示、资源容量和默认历史范围":"Resets list display, resource capacity and default history range only",
"最近 {0} 分钟":"Last {0} minutes",
"仅调整当前图表视野；摘要统计仍使用完整查询范围。":"Changes this chart view only; summaries still use the full query range.",
"P95 根据完整查询范围内有效采样桶的原始延迟中位值计算，不包含超时和缺失采样。":"P95 uses original latency medians from valid buckets across the full query range, excluding timeouts and missing samples.",
"P95 表示 95% 的有效采样延迟不高于此值。":"P95 means 95% of valid sample latencies are at or below this value.",
"{0} 个节点版本无法比较":"{0} nodes have incomparable versions",
"Hub 发布说明":"Hub release notes",
"Agent 发布说明":"Agent release notes",
"流量提醒":"Traffic reminders",
"移除筛选：{0}":"Remove filter: {0}",
"清除全部条件":"Clear all conditions",
"仅清除搜索":"Clear search only",
"到期与用量":"Expiry and usage",
"流量已用 {0}%":"Traffic used: {0}%",
"暂无到期或流量提醒":"No expiry or traffic reminders",
"收起地区":"Collapse regions",
"查看全部地区":"View all regions",
"仅记录此浏览器打开期间的观测":"Observations while this browser is open",
"应用":"Application",
"仅重置列表密度、资源容量和历史范围":"Resets list density, resource totals and history range only",
"项目主页":"Project home",
"已恢复手机显示默认设置":"Mobile display defaults restored",
"撤销":"Undo",
"显示 {0} 个节点":"Show {0} nodes",
"图表设置":"Chart settings",
"统计口径":"About these statistics",
"摘要与提示仍使用原始采样，缺失与超时保留断点。":"Summaries and tooltips use original samples; missing samples and timeouts remain gaps.",
"P95 根据完整时间范围内返回的有效原始延迟采样计算，不包含超时和缺失采样。":"P95 uses valid original latency samples returned for the full time range, excluding timeouts and missing samples.",
"丢包率使用服务端提供的完整时间范围统计，不平均各采样桶的百分比；未提供统计时不推断为零。":"Packet loss uses the server's full-range statistic, not an average of bucket percentages. Missing statistics are not treated as zero.",
"缩放只改变图表视野，不改变摘要统计范围。":"Zoom changes the chart view, not the summary time range.",
"资源历史":"Resource history",
"完整范围线路统计":"Full-range route statistics",
"最新":"Latest",
"未统计":"Not reported",
"统计：完整 {0} 小时范围":"Statistics: full {0}-hour range",
"收起缩放":"Hide zoom",
"缩放时间范围":"Zoom time range",
"恢复全范围":"Reset full range",
"无有效延迟采样":"No valid latency sample",
"当前节点":"Current node",
"不限量":"Unlimited",
"今日到期":"Expires today",
"流量额度已用尽":"Traffic allowance exhausted",
"设置":"Settings",
"筛选节点":"Filter nodes",
"全部节点":"All nodes",
"服务器运行概况":"Server health",
"需要关注":"Needs attention",
"暂无异常节点":"No nodes need attention",
"地区分布":"Regions",
"本机负载记录":"Local load history",
"让服务器状态一目了然":"Your servers at a glance",
"外观与显示":"Appearance & display",
"节点列表":"Node list",
"显示资源总容量":"Show resource capacity",
"监控偏好":"Monitoring preferences",
"默认历史范围":"Default history range",
"更多":"More",
"关于 HEX":"About HEX",
"恢复手机显示默认设置":"Reset mobile display preferences",
"主导航":"Main navigation",
"状态":"Status",
"负载优先":"Highest load first",
"重置":"Reset",
"显示结果":"Show results",
"查看网络历史":"View network history",
"流量与账单":"Traffic & billing",
"详情分区":"Node detail sections",
"总览":"Overview",
"资料":"Info",
"节点分组":"Node group",
"全部分组":"All groups",
"未分组":"Ungrouped",
"查看线路":"View route",
"地区":"Region",
"更多地区":"More regions",
"搜索地区":"Search regions",
"没有匹配的地区":"No matching regions",
"上传":"Upload",
"下载":"Download",
"未启用":"Not enabled",
"丢包率":"Packet loss",
"探测线路":"Probe route",
"系统信息":"System information",
"系统负载":"System load",
"进程数":"Processes",

"名称、状态和备注固定显示，备注位于最后一列。延迟、丢包率和探测线路可分别勾选。":"Name, status and remarks stay visible, with remarks last. Select latency, packet loss and probe route independently.",
"TCP／UDP 连接数":"TCP / UDP connections",
"费用与账期":"Price and billing cycle",
"Swap 使用率":"Swap usage",
"最近上报时间":"Last report",
"上次上报：{0}":"Last report: {0}",
"上次上报时间未知":"Last report time unknown",
"实时资源与网速暂不可用":"Live resource and network data are unavailable",
"历史数据 · 采样：{0}":"Historical data · Sample: {0}",
"较旧记录 · 采样：{0}":"Older sample · Sampled: {0}",
"查看延迟统计与历史":"View latency statistics and history",
"读取失败":"Unable to load",
"展开地图":"Expand map",
"收起地图":"Collapse map",
"增大地图高度":"Increase map height",
"缩小地图高度":"Reduce map height",

"表格显示":"Table display",
"电脑和手机分别设置，自动保存到当前浏览器。手机列较多时可左右滑动。":"Configure desktop and mobile separately. Saved in this browser. Swipe horizontally when mobile has more columns.",
"名称、状态和备注固定显示，备注位于最后一列。网络质量包含延迟和丢包。":"Name, status and remarks stay visible, with remarks last. Network quality includes latency and packet loss.",
"全选指标":"Select all metrics",
"恢复默认列":"Reset columns",
"其他列":"Other columns",

"清除搜索筛选":"Clear search filter",
"结束时间":"End time",
"拖拽移动；Ctrl / ⌘ + 滚轮缩放，全屏内直接滚轮缩放。方向键平移，+ / − 缩放。地图表示地区分组，不是机房精确位置。":"Drag to pan; Ctrl / ⌘ + wheel to zoom, or wheel in fullscreen. Arrow keys pan; + / − zoom. Regions are groups, not exact data-center locations.",
"操作说明":"Controls",
"本地观测":"Local observations",
"记录规则":"Recording rules",
"仅记录当前浏览器打开期间观测到的高负载。":"Only records high load observed while this browser is open.",
"高负载观测记录":"High-load observations",
"仅桌面生效":"Desktop only",
"修改资源样式为细条、延迟刻度为500ms、分档为150/300ms；保留已选字段和其他偏好。":"Sets resource bars, a 500ms latency scale and 150/300ms thresholds. Selected fields and other preferences are preserved.",
"上下行显示近期速率趋势，共用纵向刻度，不代表带宽使用率":"Upload and download trends share a vertical scale, not bandwidth utilization.",
"指标样式影响资源指标；首页网速显示趋势波浪线，延迟显示采样柱条。":"Style applies to resource metrics. Homepage speeds show trend lines; latency shows sample bars.",
"调整时间范围":"Change time range",
"所选范围暂不可统计":"Unavailable for this range",
"统计线路":"Summary route",
"展开其余 {0} 条线路":"Show {0} more routes",
"收起线路":"Collapse routes",
"比较线路":"Compare routes",
"历史服务暂时不可用，请稍后重试。":"History service is temporarily unavailable. Try again shortly.",
"请求过于频繁，请稍后重试。":"Too many requests. Try again shortly.",
"历史数据请求失败，请重试。":"Unable to load history. Try again.",
"读取超时，请重试。":"The request timed out. Try again.",
"网络连接失败，请重试。":"Network connection failed. Try again.",
"匹配 {0} 个节点":"{0} matching nodes",
"清除状态筛选":"Clear status filter",
"筛选离线节点":"Filter offline nodes",
"显示全部节点":"Show all nodes",
"筛选在线节点":"Filter online nodes",
"总览已收起":"Overview collapsed",
"高负载":"High load",
"收起总览":"Collapse overview",
"展开总览":"Expand overview",
"清空搜索":"Clear search",
"查看 {0} 个结果":"View {0} results",
"左右滑动查看其余指标":"Swipe to see more metrics",
"向左查看其他列":"View columns to the left",
"向右查看其他列":"View columns to the right",
"显示与偏好":"Display & preferences",
"已到期":"Expired",
"剩余 {0} 天":"{0} days left",
"{0}重置":"Resets {0}",
"{0}条线路":"{0} routes",
"恢复范围":"Reset range",
"部分数据缺失":"Some data missing",
"线路选择":"Routes",
"采样范围（最小–最大）":"Sample range (min\u2013max)",
"拖动两端缩放 · 双击恢复全范围":"Drag handles to zoom \u00b7 Double-click to reset",
"与主图时间轴同步 · 未知留空，超时单独标记":"Same time axis \u00b7 Unknown left blank, timeouts marked separately",
"当前线路：{0}":"Current route: {0}",
"统计范围：{0}–{1}":"Range: {0}\u2013{1}",
"主图、摘要与丢包轨道使用同一时间范围":"Chart, statistics and loss track share the same time range",

"采样均值":"Sample mean",
"统计说明":"About statistics",
"均值和 P95 基于当前范围内各采样桶的中位值，不代表原始探测包统计。":"Mean and P95 use bucket medians in the visible range, not individual probe packets.",
"实线表示采样中位值，阴影表示最小至最大延迟；抑制尖峰仅影响曲线。":"Lines show bucket medians; shading shows minimum to maximum latency. Spike suppression only affects the line.",
"丢包率来自完整查询窗口；缩放范围缺少样本数，暂不计算。":"Loss covers the full query window. Zoomed loss is unavailable without packet counts.",
"采样中位值":"Bucket median",
"阴影：采样范围":"Shading: sample range",
"采样范围":"Sample range",
"恢复完整范围":"Reset range",

"节点概览": "Node overview",
"资源使用": "Resource usage",
"用量与账期": "Usage and billing",
"延迟和丢包按所选线路比较；无效或旧数据排在末尾。已读取":"Latency and loss compare selected routes; invalid or old data comes last. Loaded ",
"已超额":"Over quota",
"额度 {0}": "Allowance {0}",
"流量额度使用率":"Traffic quota usage",
"查看完整节点资料：{0}":"View full node information: {0}",
"{0}排序":"Sort {0}",
"节点资料":"Node information",
"高":"High",
"中":"Medium",
"低":"Low",
"网络质量":"Network quality",
"恢复默认顺序":"Restore default order",
"降序":"Descending",
"升序":"Ascending",
"表格排序":"Table sorting",
"名称与状态始终保留；仅影响当前设备的表格。":"Name and status stay visible. Applies only to this device’s table.",
"独立列":"Separate columns",
"分组显示":"Grouped columns",
"列布局":"Column layout",
"费用":"Billing",
"概览":"Overview",
"桌面表格":"Desktop table",
"手机表格":"Mobile table",
"实时上行":"Live upload",
"实时下行":"Live download",
"延迟采样 · 统一刻度 0–{0} ms；黄色 ≥{1}，红色 ≥{2}":"Latency samples · shared scale 0–{0} ms; amber ≥{1}, red ≥{2}",
"首页延迟统计":"Home latency statistics",
"首页延迟窗口":"Home latency window",
"最近 1 小时":"Last 1 hour",
"最近 6 小时":"Last 6 hours",
"最近 24 小时":"Last 24 hours",
"延迟统一刻度":"Shared latency scale",
"黄色阈值（ms）":"Amber threshold (ms)",
"红色阈值（ms）":"Red threshold (ms)",
"应用延迟阈值":"Apply latency thresholds",
"阈值须满足：1 ≤ 黄色 < 红色 ≤ 5000 ms":"Thresholds must satisfy: 1 ≤ amber < red ≤ 5000 ms",
"所有首页卡片共用刻度。超出刻度的采样封顶标红，实际数值保留；叉号代表超时，空隙代表缺失。":"All home cards share the scale. Above-scale samples are capped and red, with actual values retained; crosses mean timeout and gaps mean missing data.",
"指标样式仅影响 CPU、内存和硬盘；首页网速固定分段条，延迟固定采样柱条。":"Indicator styles affect CPU, memory and disk only. Home network rates use fixed activity segments and latency uses sample bars.",

"恢复之前选择":"Restore previous selection",
"仅看：{0}":"Only show: {0}",
"仅看此线路":"Only show this route",
"上次成功更新：{0}":"Last successful update: {0}",
"正在更新":"Updating",
"保留上次记录":"Previous data",
"更新失败":"Update failed",
"更新于 {0}":"Updated {0}",
"关闭图表提示":"Close chart tooltip",
"展开名称":"Expand name",
"收起名称":"Collapse name",
"搜索线路":"Search routes",
"按名称搜索":"Search by name",
"没有匹配的线路":"No matching routes",
"详情页": "Detail page",
"设备资料展开方式": "Device information display",
"自动：手机折叠，桌面展开": "Auto: collapse on mobile",
"展开": "Expanded",
"折叠": "Collapsed",
"自动模式仅在手机端折叠；PC端始终展开，手动选择会在手机端记住。": "Auto collapses on mobile only; desktop is always expanded. Manual choices are remembered on mobile.",
"恢复外观保留显示内容与详情展开方式；全部重置将恢复站点默认并清空线路偏好和筛选。": "Reset appearance keeps display content and device information preferences. Reset all restores site defaults and clears route preferences and filters.",
"收起备注": "Collapse notes",
"展开备注": "Expand notes",
"网络与流量": "Network and traffic",
"费用与到期": "Billing and expiry",
"硬件与系统": "Hardware and system",
"选择线路": "Select routes",
"已选 {0} / {1}": "{0} / {1} selected",
"显示预设": "Display preset",
"完整": "Full",
"精简": "Slim",
"自定义": "Custom",
"通用显示预设": "General display presets",
"手机显示预设": "Mobile display presets",
"显示全部辅助信息": "Show all additional information",
"隐藏连接数与在线时长": "Hide connections and uptime",
"常用外观": "Common appearance",
"指标与图标": "Metrics and icons",
"仅保存在当前浏览器；未修改的选项跟随站点默认。": "Saved in this browser only. Unchanged options follow site defaults.",
"手机正在使用上方通用设置；切换为单独设置后可独立调整。": "Mobile uses the general settings above. Choose separate settings to customize it independently.",
"恢复外观保留卡片信息、手机方案与列数；全部重置将恢复站点默认并清空线路偏好和筛选。": "Reset appearance keeps card information, mobile settings and columns. Reset all restores site defaults and clears route preferences and filters.",
"暂无可用历史数据": "No history is available.",
"更新失败，保留上次历史记录。": "Update failed. Showing the last history. ",
"正在读取历史数据": "Loading history",
"正在加载节点": "Loading nodes",
"高级外观": "Advanced appearance",
"仅影响宽度不超过 720px 的首页卡片。": "Applies to home cards at widths up to 720px.",
"单独设置": "Custom settings",
"跟随通用设置": "Follow general settings",
"手机显示": "Mobile display",
"手机卡片信息": "Mobile card information",
"通用卡片信息": "General card information",
"卡片信息": "Card information",
"{0} 列": "{0} columns",
"自动": "Automatic",
"桌面列数": "Desktop columns",
"价格": "Price",
"备注标签": "Remark tags",
"到期信息": "Expiry information",
"TCP／UDP": "TCP / UDP",
"网速": "Network",
"显示内容": "Display",
"提醒": "Alerts",
"偏好管理": "Preferences management",
"CPU 达到 85% 时记录，低于 80% 时标记恢复。记录仅保存在当前浏览器。": "Recorded at 85% CPU; marked recovered below 80%. History stays in this browser.",
"复制失败，请手动选择文本": "Copy failed; select the text manually",
"已复制": "Copied",
"复制：{0}": "Copy: {0}",
"恢复默认位置": "Reset default position",
"最后成功获取：{0}": "Last successful fetch: {0}",
"此告警时段没有返回历史样本。": "No history samples were returned for this alert period.",
"当前历史范围无法覆盖完整告警时段。": "The selected history range does not cover the entire alert period.",
"告警时段：{0} — {1}": "Alert period: {0} \u2014 {1}",
"查看 CPU 历史": "View CPU history",
"查看线路：{0}": "View route: {0}",
"今天到期": "Expires today",
"流量用量 / 总额度": "Traffic used / allowance",
"全局：{0}": "Global: {0}",
"到期": "Expiry",
"资源指标": "Resource metric",
"关闭": "Close",
"记录未持久保存": "Records are not saved persistently",
"查看高负载记录详情": "View high load details",
"查看高负载记录": "View high load history",
"CPU 峰值": "Peak CPU",
"持续时长": "Duration",
"最后观测": "Last observed",
"恢复时间": "Recovered at",
"开始时间": "Started",
"暂无高负载记录": "No high load records",
"浏览器存储不可用，记录仅在本次页面内保留。": "Browser storage unavailable. Records last only for this page session.",
"仅保存在当前浏览器，保留最近 100 条结束记录；页面关闭期间不监测。": "Stored in this browser only, with the latest 100 ended records retained. Monitoring stops when the page is closed.",
"CPU ≥85% 触发，低于 80% 恢复。记录从首次观测起计时；中断时仅统计已观测时段。": "CPU \u226585% triggers an alert; below 80% resolves it. Duration starts at first observation and excludes unobserved gaps.",
"高负载记录": "High load history",
"监测中断": "Monitoring interrupted",
"已恢复": "Recovered",
"告警中": "Active",
"等待数据": "Waiting for data",
"{0} 个节点暂无实时数据": "Live data unavailable for {0} nodes",
"恢复跟随全局线路": "Follow global route again",
"即时预览；未单独修改的选项跟随站点默认": "Live preview; unchanged options follow site defaults.",

  "丢包暂无统计": "Packet loss unavailable",
  "逐点丢包暂无统计": "Per-sample packet loss unavailable",
  "查看完整备注": "View full notes",
  "备注": "Notes",
  "首页总网速样式": "Home total speed style",
  "相对峰值仪表": "Relative peak gauge",
  "全局外观": "Global appearance",
  "仅影响首页顶部实时网速；卡片与详情页使用统一指示条。": "Only affects the home summary. Cards and details use shared speed indicators.",
  "数据已过期，上次上报：{0}": "Stale data. Last report: {0}",
  "数据已过期": "Stale data",
  "上下行共用近期峰值，指示长度不代表带宽使用率": "Upload and download share a recent peak scale; length is not bandwidth utilization.",

  "抑制尖峰": "Suppress spikes",
  "历史数据": "Historical data",
  "近期趋势": "Recent trend",
  "部分离线": "Partly offline",
  "全部离线": "All offline",
  "地图说明": "Map information",
  "地图仅表示国家或地区，不是机房精确位置。未知地区和小地区可从列表选择。": "The map represents countries or regions, not exact server locations. Use the list for small or unknown regions.",
  "关闭设置": "Close settings",
  "设置分类": "Settings sections",
  "外观": "Appearance",
  "首页": "Overview",
  "恢复外观仅重置配色、背景与样式；全部重置还会清空线路偏好和筛选。": "Restore appearance resets colours, background and styles only. Reset all also clears route preferences and filters.",

  "设备资料": "Device information",
  "流量与到期": "Traffic and renewal",
  "流量配额": "Traffic allowance",
  "流量重置": "Traffic reset",
  "每月 {0} 日": "Day {0} of each month",
  "实时指标": "Live metrics",
  "历史图表": "History charts",
  "图表类型": "Chart type",
  "延迟图表选项": "Latency chart options",
  "时间范围": "Time range",
  "抑制尖峰仅改变图线显示，不修改原始数据。": "Spike suppression only changes the displayed line, not the original data.",
  "已启用平滑，仅影响图线显示": "Smoothing enabled; original data is unchanged",
  "前往后台添加节点": "Add nodes in admin panel",
  "请联系管理员添加节点。": "Contact an administrator to add nodes.",
  "首页线路": "Home route",
  "丢包统计范围：{0} 小时": "Loss window: {0} hours",

  "节点独立选择优先于全局线路；其余线路可在详情查看。": "Per-node choices override this default; other routes are available in details.",
  "1 分钟 · {0} 核": "1 min · {0} cores",
  "在线时长": "Uptime",

"跟随全局：{0}": "Global: {0}",
"查看全部 {0} 条线路": "View all {0} routes",
"各节点所选线路可能不同，延迟比较请注意探测目标。": "Nodes may use different routes; consider probe targets when comparing latency.",
"天": "d",
"延迟": "Latency",
"绿 <80ms；黄 <160ms；橙 <220ms；红 ≥220ms 或超时。": "Green <80ms; yellow <160ms; orange <220ms; red ≥220ms or timeout.",
"分组": "Group",
"重置排序": "Reset order",
"刷新延迟": "Refresh latency",
"高负载提示": "High load alerts",
"更多信息": "More information",
"清除地区筛选": "Clear region filter",
"清除系统筛选": "Clear system filter",
"高负载提醒：{0} · CPU {1}%": "High load: {0} · CPU {1}%",
  "5 / 15 分钟": "5 / 15 min",
  "显示 {0}/{1} 个节点": "Showing {0}/{1} nodes",
  "排序方向": "Sort direction",
  "默认风格": "Default",
  "默认展开多线路": "Expand all probes by default",
  "快捷操作": "Quick actions",
  "系统快速筛选": "Quick system filters",
  "地区快速筛选": "Quick region filters",
  "正在刷新延迟": "Refreshing latency",
  "刷新当前节点延迟": "Refresh filtered nodes",
  "完成 {0}/{1}，失败 {2}": "Completed {0}/{1}, failed {2}",
  "页面显示异常": "Unable to display this page",
  "请刷新页面重试，或返回首页。": "Refresh this page or return to the overview.",
  "返回首页": "Back to overview",
  "视觉风格": "Visual style",
  "原始风格": "Original",
  "手机布局": "Mobile layout",
  "跟随卡片布局": "Follow card layout",
  "节点探测线路": "Node probe",
  "跟随全局线路": "Follow global probe",
  "最新采样": "Latest sample",
  "24h 丢包": "24h loss",
  "负载": "Load",
  "1 / 5 / 15 分钟": "1 / 5 / 15 min",
  "架构 / 虚拟化": "Architecture / virtualization",
  "实时状态": "Live status",
  "当前数据": "Current data",
  "实时使用率": "Live utilization",
  "批量线路操作": "Bulk probe actions",
  "显示全部线路": "Show all probes",
  "隐藏全部线路": "Hide all probes",
  "已启用削峰，仅影响图线显示": "Despiking enabled; only the displayed line is adjusted",
  "{0} 个采样桶": "{0} sample buckets",
  "空白表示缺样或超时；超过两小时的缺口不连线。采样桶数不是原始探测次数。": "Gaps indicate missing samples or timeouts; gaps over two hours are not connected. Bucket counts are not raw probe counts.",
  "节点浏览": "Browse nodes",
  "筛选与排序": "Filters & sorting",
  "已分组": "Grouped",
  "自选线路": "Custom probe",
  "较旧记录": "Stale samples",
  "采样信息": "Sample details",
  "网络错误": "Network error",
  "加载失败：": "Unable to load: ",
  "重试": "Retry",
  "加载中…": "Loading…",
  "外观设置": "Appearance",
  "进入后台": "Admin panel",
  "登录": "Sign in",
  "切换主题": "Switch theme",
  "切换明暗模式": "Toggle light / dark",
  "连接异常，正在重试。": "Connection error. Retrying. ",
  "返回总览": "Back to overview",
  "上一个节点": "Previous node",
  "切换节点": "Switch node",
  "下一个节点": "Next node",
  "节点不存在或未公开。": "Node not found or not public. ",
  "返回列表": "Back to list",
  "服务器总览": "Server overview",
  "一目了然，即刻掌握。": "Your infrastructure at a glance.",
  "正在连接": "Connecting",
  "实时连接": "Live connection",
  "轮询更新": "Polling updates",
  "连接中断 · 数据可能已过期": "Disconnected · Data may be stale",
  "最后更新：{0}": "Last update: {0}",
  "等待首次数据": "Waiting for first update",
  "搜索节点": "Search nodes",
  "搜索名称、地区、操作系统…": "Search name, region, operating system…",
  "清除搜索": "Clear search",
  "返回顶部": "Back to top",
  "卡片视图": "Card view",
  "卡片": "Cards",
  "地图视图": "Map view",
  "地图": "Map",
  "表格视图": "Table view",
  "表格": "Table",
  "全部": "All",
  "在线": "Online",
  "离线": "Offline",
  "筛选地区": "Filter region",
  "所有地区": "All regions",
  "未知地区": "Unknown region",
  "个节点": " nodes",
  "系统分组": "System filter",
  "所有系统": "All systems",
  "其他 / 未知系统": "Other / unknown OS",
  "卡片分组": "Card grouping",
  "不分组": "No grouping",
  "按地区": "By region",
  "按系统": "By system",
  "按当前筛选估算 · 各币种单独汇总": "Current filter · Separate totals per currency",
  "排序": "Sort",
  "排序字段": "Sort field",
  "切换排序方向": "Reverse sort direction",
  "升序 ↑": "Ascending ↑",
  "降序 ↓": "Descending ↓",
  "恢复默认排序": "Restore default order",
  "主要探测": "Primary probe",
  "主要探测线路": "Primary probe selection",
  "各节点首条线路": "First probe on each node",
  "线路": "Probe ",
  "（等待数据）": " (waiting for data)",
  "显示列": "Visible columns",
  "表格列": "Table columns",
  "延迟采用所选线路的最新采样桶；超时、旧记录和无数据排在末尾。已读取": "Uses the latest bucket for the selected probe. Timeouts, stale and missing values appear last. Loaded ",
  "个节点。": " nodes.",
  "当前各节点首条线路可能不同，可选择同一线路进行比较。": "First probes may target different hosts. Select the same probe to compare nodes.",
  "还没有节点": "No nodes yet",
  "没有符合条件的节点": "No matching nodes",
  "清除筛选": "Clear filters",
  "正在加载…": "Loading…",
  "· 浏览器本地日期": " · Browser local date",
  "剩余价值估算 ·": "Estimated remaining value · ",
  "个": " nodes",
  "一次性标价 ·": "One-time listed price · ",
  "显示": "Show",
  "已过期": "Expired",
  "即将到期": "Expiring soon",
  "正常": "Normal",
  "节点": "Nodes",
  "价格未知": "Unknown price",
  "未设到期日": "No expiry date",
  "已过期 {0} 天": "Expired {0} days ago",
  "剩余价值 = 周期价格 × 剩余日历天数 ÷ 假定周期天数。以到期日向前减一个日历周期，月末超出日期时截到该月最后一天；不把一个月固定当作 30 天。": "Remaining value = cycle price × remaining calendar days / assumed cycle days. The cycle starts one calendar period before expiry, clamped to the last day of the target month. A month is not treated as a fixed 30 days.",
  "未设到期": "Expiry not set",
  "{0} 天后到期": "Expires in {0} days",
  "查看 {0}": "View {0}",
  "等待首次上报": "Waiting for first report",
  "等待指标": "Waiting for metrics",
  "未连接": "Not connected",
  "CPU · {0} 核": "CPU · {0} cores",
  "负载 {0}": "Load {0}",
  "暂无数据": "No data",
  "内存": "Memory",
  "容量 {0}": "Capacity {0}",
  "硬盘": "Disk",
  "处理器": "Processor",
  "架构": "Architecture",
  "负载 1 / 5 / 15": "Load 1 / 5 / 15",
  "交换空间": "Swap",
  "实时网速": "Live speed",
  "累计流量": "Total traffic",
  "本月用量": "Monthly usage",
  "当前周期用量": "Current cycle usage",
  "流量周期：每月 {0} 日重置，本周期自 {1} 起": "Traffic cycle resets on day {0} of each month; current cycle starts {1}",
  "延迟统计与历史": "Latency statistics and history",
  "服务器": "Server",
  "1 小时": "1 hour",
  "6 小时": "6 hours",
  "24 小时": "24 hours",
  "7 天": "7 days",
  "资源": "Resources",
  "网络延迟": "Network latency",
  "探测 {0}": "Probe {0}",
  "系统": "System",
  "{0} 核": "{0} cores",
  "内存 / 硬盘": "Memory / disk",
  "{0} 进程": "{0} processes",
  "今日流量": "Today's traffic",
  "续费": "Renewal",
  "零价：免费或未填写": "Zero price: free or unset",
  "{0} 到期": "Expires {0}",
  "刷新历史": "Refresh history",
  "削峰": "Remove spikes",
  "读取历史数据失败：": "Unable to load history: ",
  "这段时间没有延迟数据": "No latency data in this range",
  "没有选中任何探测": "No probes selected",
  " · 丢 {0}%": " · Loss {0}%",
  "丢": "Loss ",
  "这段时间没有历史数据": "No history in this range",
  "内存 · {0}": "Memory · {0}",
  "网络速率": "Network speed",
  "下行": "Download",
  "上行": "Upload",
  "硬盘 · {0}": "Disk · {0}",
  "刷新延迟数据": "Refresh latency data",
  "刷新": "Refresh",
  "读取": "Read ",
  "读取失败 · 重试": "Read failed · Retry",
  "读取中…": "Loading…",
  "无该线路记录": "No records for this probe",
  "超时": "Timeout",
  "· 丢包": " · Loss ",
  "采样": "Sample ",
  " · 较旧": " · Stale",
  "节点表格，可横向滚动": "Node table, horizontally scrollable",
  "24 小时延迟统计": "24-hour latency statistics",
  "延迟统计（24h）": "Latency statistics (24h)",
  "更新失败 · 上次数据": "Update failed · Previous data",
  "暂不可用 · 自动重试": "Unavailable · Retrying",
  "最近成功读取接口的时间，不是探测采样时间；可见时每分钟刷新": "Last successful API read, not probe sample time; refreshes every minute while visible",
  "· 每分钟刷新": " · Refreshes every minute",
  "无法读取探测记录": "Unable to read probe records",
  "正在读取探测记录…": "Loading probe records…",
  "暂无探测记录": "No probe records",
  "收起其他线路": "Collapse other probes",
  "展开全部 {0} 条线路": "Show all {0} probes",
  "相邻有效采样桶延迟的平均绝对差；不是原始探测抖动": "Mean absolute change between adjacent valid buckets, not raw probe jitter",
  "ms 波动": " ms variation",
  " · 较旧记录": " · Stale record",
  "最新采样桶：{0}": "Latest sample bucket: {0}",
  "延迟历史，由旧到新": "Latency history, oldest to newest",
  "丢包": "Packet loss",
  "服务端统计的整个 24 小时窗口丢包率": "Server-calculated loss across the entire 24-hour window",
  "丢包历史，由旧到新": "Loss history, oldest to newest",
  "未知": "Unknown",
  "{0}% 丢包": "{0}% loss",
  "绿 <80ms；黄 <160ms；橙 <220ms；红 ≥220ms 或超时。色条为最近采样，不代表等间隔时间。": "Green <80ms; yellow <160ms; orange <220ms; red ≥220ms or timeout. Bars are recent samples, not equally spaced time intervals.",
  "最近 40 个采样桶 · 颜色说明": "Latest 40 buckets · Color guide",
  "历史曲线": "History chart",
  "24h 窗口内采样 ·": "Samples within 24h · ",
  "纵轴上限 {0} ms": "Y-axis maximum {0} ms",
  "全部超时": "All timed out",
  "探测延迟历史曲线": "Probe latency history chart",
  "横轴按采样时间；红叉为超时，长缺口断开。": "X-axis follows sample time; red crosses mark timeouts and long gaps are disconnected.",
  "背景图片地址": "Background image URL",
  "https://… 或 /background.svg": "https://… or /background.svg",
  "请输入 HTTP(S) 地址或站内绝对路径": "Enter an HTTP(S) URL or an absolute site path",
  "应用背景": "Apply background",
  "让面板更像你": "Make this dashboard yours",
  "即时预览，自动保存在当前浏览器": "Live preview, saved automatically in this browser",
  "外观与首页": "Appearance & overview",
  "界面与卡片": "Interface & cards",
  "主题配色": "Color palette",
  "明暗模式": "Color mode",
  "跟随系统": "Follow system",
  "浅色": "Light",
  "深色": "Dark",
  "卡片布局": "Card layout",
  "指标样式": "Metric style",
  "卡片密度": "Card density",
  "舒适": "Comfortable",
  "紧凑": "Compact",
  "网速展示": "Speed display",
  "趋势线": "Trend line",
  "仪表盘": "Gauge",
  "显示已用 / 总容量": "Show used / total capacity",
  "国旗与系统图标": "Flags and system icons",
  "背景与质感": "Background & effects",
  "使用内置山峦": "Use built-in mountains",
  "清除背景": "Clear background",
  "背景加载失败，已使用默认底色。请检查图片地址。": "Background failed to load. Using the default color. Check the image URL.",
  "背景效果": "Background effect",
  "柔和模糊": "Soft blur",
  "玻璃质感": "Glass effect",
  "背景模糊": "Background blur",
  "背景遮罩": "Background overlay",
  "开启卡片毛玻璃": "Enable frosted cards",
  "卡片不透明度": "Card opacity",
  "卡片模糊": "Card blur",
  "手机端会降低模糊强度。外部背景图片仅在设置后加载。": "Blur is reduced on mobile. External background images load only after being configured.",
  "首页模块": "Overview modules",
  "外观偏好已导出，不包含节点或账号信息": "Appearance exported without node or account information",
  "导出外观偏好": "Export appearance",
  "导入外观偏好": "Import appearance",
  "配置文件不能超过 64 KB": "Configuration must not exceed 64 KB",
  "外观偏好已导入": "Appearance imported",
  "导入失败": "Import failed",
  "外观已恢复站点默认，首页模块和筛选已保留": "Site appearance restored; modules and filters kept",
  "恢复默认外观": "Restore default appearance",
  "全部本地偏好已恢复，浏览筛选已清空": "Local preferences reset and browse filters cleared",
  "重置全部偏好": "Reset all preferences",
  "重置全部偏好？": "Reset all preferences?",
  "将恢复站点默认外观与显示设置，并清除表格列、语言、线路偏好和浏览筛选。此操作无法撤销。": "Restore the site defaults and clear table columns, language, route preferences, and browse filters. This cannot be undone.",
  "确认重置": "Reset preferences",
  "节点离线 · 线路探测独立更新": "Agent offline · route probes update independently",
  "取消": "Cancel",
  "主题配置包含外观、显示、网络、表格列、语言、节点线路偏好与地图高度；不包含账号、节点数据或临时筛选。": "Theme settings include appearance, display, network, table columns, language, node routes, and map height. Accounts, node data, and temporary filters are excluded.",
  "导出主题配置": "Export theme settings",
  "导入主题配置": "Import theme settings",
  "主题配置已导出": "Theme settings exported",
  "主题配置已导入": "Theme settings imported",
  "旧版外观偏好已导入": "Legacy appearance settings imported",
  "导出失败": "Export failed",
  "配置文件不能超过 256 KB": "Configuration must not exceed 256 KB",
  "配置缺少主题设置": "Theme settings are missing",
  "配置缺少表格设置": "Table settings are missing",
  "表格设置格式不正确": "Invalid table settings",
  "语言设置格式不正确": "Invalid language setting",
  "地图设置格式不正确": "Invalid map setting",
  "线路偏好格式不正确": "Invalid route preferences",
  "当前时间": "Current time",
  "· 本地时间": " · Local time",
  "{0} 个离线": "{0} offline",
  "全部在线": "All online",
  "最忙节点": "Busiest node",
  "无在线节点": "No online nodes",
  "总流量": "Total traffic",
  "仪表比例相对于最近 60 个有效快照的总速率峰值，不代表带宽使用率": "Gauge compares current total speed with the peak of the last 60 valid snapshots, not link capacity",
  "相对近期峰值": "Relative to recent peak",
  "地区统计": "Region statistics",
  "个地区": " regions",
  "个节点未定位": " nodes without a region",
  "全球节点分布": "Global node distribution",
  "悬停或聚焦查看节点，点击筛选地区": "Hover or focus to preview nodes; click to filter a region",
  "个地区 ·": " regions · ",
  "世界节点分布地图": "World node distribution map",
  "{0}：{1} / {2} 在线": "{0}: {1} / {2} online",
  "地区节点详情": "Region node details",
  "筛选此地区": "Filter this region",
  "绿色：全部在线 · 橙色：部分离线 · 灰色：全部离线。未知地区单独列出；小地区可从列表选择。标记仅代表国家或地区，不是机房精确位置。": "Green: all online · Orange: partly offline · Gray: all offline. Unknown regions are listed separately; small regions can be selected from the list. Markers represent countries or regions, not precise datacenter locations.",
  "{0} 天 {1} 小时": "{0}d {1}h",
  "{0} 小时 {1} 分": "{0}h {1}m",
  "{0} 分": "{0}m",
  "月付": "Monthly",
  "季付": "Quarterly",
  "半年付": "Semiannual",
  "年付": "Annual",
  "两年付": "Two-year",
  "三年付": "Three-year",
  "一次性": "One-time",
  "经典蓝": "Classic blue",
  "海洋": "Ocean",
  "落日": "Sunset",
  "森林": "Forest",
  "午夜": "Midnight",
  "玫瑰": "Rose",
  "经典": "Classic",
  "现代": "Modern",
  "极简": "Minimal",
  "详细": "Detailed",
  "紧凑行": "Compact row",
  "圆环": "Ring",
  "进度条": "Progress bar",
  "分段柱条": "Segmented columns",
  "极简数字": "Minimal numbers",
  "在线节点": "Online nodes",
  "流量统计": "Traffic statistics",
  "首页地图": "Overview map",
  "文件不是有效的 JSON 配置": "Invalid JSON configuration",
  "配置必须是一个对象": "Configuration must be an object",
  "不支持此配置版本": "Unsupported configuration version",
  "没有可用的外观设置": "No usable appearance settings",
  "背景仅支持 HTTP(S) 地址或站内绝对路径": "Backgrounds require HTTP(S) URLs or absolute site paths",
  "延迟数据格式异常": "Invalid latency data",
  "延迟数据暂不可用": "Latency data temporarily unavailable",
  "后台默认": "Backend order",
  "名称": "Name",
  "在线状态": "Online status",
  "上传速度": "Upload speed",
  "下载速度": "Download speed",
  "所选线路延迟": "Selected probe latency",
  "到期时间": "Expiry date",
  "{0} 离线 · {1} 待更新": "{0} offline · {1} awaiting update",
  "首页线路数量": "Home route count",
  "近期延迟采样": "Recent latency samples",
  "IP 协议": "IP protocols",
 "放大地图":"Zoom in",
 "缩小地图":"Zoom out",
 "适配全部":"Fit all",
 "退出全屏":"Exit fullscreen",
 "全屏地图":"Fullscreen map",
 "拖拽移动；Ctrl / ⌘ + 滚轮缩放，全屏内直接滚轮缩放。地图表示地区分组，不是机房精确位置。":"Drag to pan; Ctrl / ⌘ + scroll to zoom, or scroll directly in fullscreen. Locations represent regions, not exact datacentres.",
  "选择地区": "Select region",
  "{0} 个节点": "{0} nodes",
  "积累数据中":"Collecting samples",
  "最近 60 秒网速":"Network speed over the last 60 seconds",
  "最近 60 秒":"Last 60s",
  "最近 {0} 分钟 · 采样趋势":"Last {0} min · sampled trend",
  "丢包时间轨道":"Packet loss timeline",
  "丢包线路":"Loss route",
  "查看丢包采样":"Inspect packet loss sample",
  "正在读取…":"Loading…",
  "线路图例":"Route legend",
  "采样：{0}":"Sample: {0}",
  "已选 {0} / {1} 条线路":"{0} / {1} routes selected",
  "免费 / 未填写":"Free / unspecified",
  "部分时段缺少逐点丢包数据":"Some intervals have no per-sample packet loss data",
  "收起资料":"Hide details",
  "更多资料":"More details",
  "网络":"Network",
  "其他":"Other",
  "偏好":"Preferences",
  "已应用推荐显示":"Recommended display applied",
  "应用本站推荐显示":"Apply recommended display",
  "概览资料 · 资源细条 · 500ms 刻度 · 150/300ms 分档；其他偏好保留。":"Overview details · resource bars · 500ms scale · 150/300ms bands; other preferences are preserved.",
  "资料密度":"Information density",
  "概览：辅助资料按需展开":"Overview: expand secondary details as needed",
  "完整：显示全部已选资料":"Full: show all selected details",
  "辅助信息方案":"Additional information plan",
  "延迟分档":"Latency profile",
  "高负载提示在 CPU 达到 85% 时记录，低于 80% 时标记恢复；记录仅保存在当前浏览器。":"High load alerts record at 85% CPU and recover below 80%; records stay in this browser.",
  "原有分档 80/160ms":"Original bands 80/160ms",
  "跨境参考 150/300ms":"Cross-border reference 150/300ms",
  "仅用于视觉分档，不改变后台告警阈值。":"Display bands only; server alert thresholds are unchanged.",
  "阈值修改尚未应用":"Threshold changes have not been applied",
  "关闭搜索":"Close search",
  "找到 {0} 个节点":"{0} nodes found",
  "查找线路":"Find routes",
  "没有符合条件的线路":"No matching routes",
  "合并相关指标":"Combine related metrics",
  "每项独立一列":"Separate columns",
  "合并显示上下行速度，桌面状态并入名称；手机状态始终跟随名称。":"Combine upload and download; include desktop status in the name. Mobile status always stays with the name.",
  "查看备注：{0}":"View remarks: {0}",
  "表格分页":"Table pagination",
  "共 {0} 个节点 · 每页 20 个":"{0} nodes · 20 per page",
  "上一页":"Previous",
  "下一页":"Next",
  "页码":"Page",
  "第 {0} / {1} 页":"Page {0} of {1}",
 "地图暂时无法加载":"Map is temporarily unavailable",
 "地图加载较慢，节点列表仍可使用":"The map is loading slowly. The node list is still available.",
 "地图加载中…":"Loading map…",
 "重试地图":"Retry map",
 "刷新页面":"Reload page",
 "等待节点数据":"Waiting for node data",
"版本与更新":"Versions & updates",
"正在检查…":"Checking…",
"检查更新":"Check for updates",
"前往后台更新":"Open admin updates",
"尚未检查":"Not checked",
"最近检查：{0}":"Last checked: {0}",
"当前版本":"Current version",
"最新版本":"Latest version",
"发布说明":"Release notes",
"有新版本":"Update available",
"已是最新版本":"Up to date",
"当前版本高于发布版本":"Current version is newer than the release",
"版本无法比较":"Versions cannot be compared",
"尚未上报版本":"Version not reported",
"最新版本暂不可用":"Latest version unavailable",
"{0} 个节点可更新":"{0} nodes can be updated",
"{0} 个节点尚未上报版本":"{0} nodes have not reported a version",
"节点版本":"Node versions",
"主题":"Theme",
"主题管理":"Theme management",
"主题更新请在后台主题管理中查看。":"Check theme updates in admin theme management.",
"这里只检查版本，升级操作请前往后台完成。":"This panel only checks versions. Complete upgrades in the admin panel.",
"版本信息由后台缓存，重复检查不会强制刷新发布源。":"Version information is cached by the server. Rechecking does not force a refresh from the release source.",
"登录已失效，请重新登录":"Your session expired. Please sign in again.",
"当前后台暂不支持版本查询":"This server does not support version checks yet.",
"检查失败，请稍后重试":"Check failed. Please try again later.",
"检查未完成":"Check incomplete",
"查看版本":"View versions"
}
