import {expandRoutes} from './routes'
import {chooseOption} from './select'
import {test,expect} from '@playwright/test'
import {nodes,metrics} from '../scripts/fixtures.mjs'
async function setup(page:any) {
 await page.addInitScript(()=>{
  localStorage.setItem('monitor-next',JSON.stringify({designVersion:1,probe:'1'}))
  localStorage.setItem('monitor-next-node-probes-v1',JSON.stringify({'1':'2'}))
 })
 await page.route('**/api/nodes/*/metrics?*',(r:any)=>{const d=metrics();return r.fulfill({json:{...d,ping:[{task_id:1,ts:Date.now()/1000-60,latency:20},{task_id:1,ts:Date.now()/1000,latency:25},{task_id:2,ts:Date.now()/1000-60,latency:80},{task_id:2,ts:Date.now()/1000,latency:90}],probes:{1:'Route A',2:'Route B',3:'Empty route'},loss:{2:2.5}}})})
 await page.goto('/node/1#latency')
 await expect(page.locator('.route-chips')).toHaveCount(0);await expandRoutes(page);await expect(page.locator('.route-chips button[aria-pressed]')).toHaveCount(3)
}
test('detail follows the global route despite a node override and supports comparison',async({page})=>{
 await setup(page)
 const a=page.locator('.route-chips button[aria-label="Route A"]'),b=page.locator('.route-chips button[aria-label="Route B"]')
 await expect(a).toHaveAttribute('aria-pressed','true');await expect(b).toHaveAttribute('aria-pressed','false')
 await expect(page.locator('.detail-chart-frame .recharts-line-curve')).toHaveCount(1)
 await expect(page.getByLabel('抑制尖峰')).not.toBeChecked()
 const frame=page.locator('.detail-chart-frame');const height=(await frame.boundingBox())!.height
 await b.click();await expect(b).toHaveAttribute('aria-pressed','true');await expandRoutes(page)
 await expect(page).toHaveURL(/routes=1%2C2/)
 await frame.hover({position:{x:100,y:100}})
 expect((await frame.boundingBox())!.height).toBe(height)
 await page.getByLabel('抑制尖峰').check()
 expect((await frame.boundingBox())!.height).toBe(height)
 await expandRoutes(page);await expect(page.locator('.probe-bulk-actions,.route-search,.probe-solo,.probe-restore')).toHaveCount(0)
 const empty=page.locator('.route-chips button[aria-label="Empty route"]');await empty.click();await expect(empty).toHaveAttribute('aria-pressed','true')
 expect((await frame.boundingBox())!.height).toBe(height)
 await expect(empty).toBeFocused()
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('monitor-next-node-probes-v1')!)['1'])).toBe('2')
 await page.getByRole('button',{name:'1 小时',exact:true}).click()
 await expandRoutes(page);await expect(page.locator('.detail-chart-frame .recharts-line-curve')).toHaveCount(3)
 await expect(b).toHaveAttribute('aria-pressed','true')
 expect((await page.evaluate(()=>JSON.parse(localStorage.getItem('monitor-next')||'{}'))).probe).toBe('1')
})
test('route selector switches one route, all routes, and the global default without changing stored choices',async({page})=>{
 await setup(page)
 const controls=page.locator('.latency-route-controls'),route=controls.getByLabel('查看线路',{exact:true}),a=page.locator('.route-chips button[aria-label="Route A"]'),compare=controls.locator('.expand-routes')
 await expect(page.getByLabel('查看线路',{exact:true})).toHaveCount(1)
 await expect(page.locator('.detail-chart-toolbar').getByLabel('查看线路',{exact:true})).toHaveCount(0)
 await expect(route).toHaveAttribute('data-value','auto')
 await chooseOption(route,'2')
 await expect(route).toHaveAttribute('data-value','2');await expect(compare).toHaveAttribute('aria-expanded','false')
 await expect(page.locator('.route-chips')).toHaveCount(0)
 await expect(page).toHaveURL(/routes=2/)
 await compare.click();await expect(compare).toHaveAttribute('aria-expanded','true');await expect(a).toHaveAttribute('aria-pressed','false')
 await chooseOption(route,'all');await expect(page).toHaveURL(/routes=all/)
 await expect(compare).toHaveAttribute('aria-expanded','false')
 await expect(page.locator('.detail-chart-frame .recharts-line-curve')).toHaveCount(3)
 await chooseOption(route,'auto')
 await expect(route).toHaveAttribute('data-value','auto');await expect(page.locator('.route-chips')).toHaveCount(0)
 await expect(page).not.toHaveURL(/routes=/)
 const stored=await page.evaluate(()=>({global:JSON.parse(localStorage.getItem('monitor-next')||'{}').probe,node:JSON.parse(localStorage.getItem('monitor-next-node-probes-v1')||'{}')['1']}))
 expect(stored).toEqual({global:'1',node:'2'})
 await page.goto('/node/1?routes=2#latency');await expect(page.getByLabel('查看线路',{exact:true})).toHaveAttribute('data-value','2')
 await expect(page.locator('.route-chips')).toHaveCount(0)
})
test('detail prioritizes charts, renders complete facts and compact controls at all widths',async({page})=>{
 await setup(page)
 for(const width of [768,1440]) {
  await page.setViewportSize({width,height:1000})
  const live=await page.locator('.detail-live').boundingBox(),history=await page.locator('.detail-history').boundingBox(),facts=await page.locator('.detail-information').boundingBox()
  if(width<900){expect(facts!.y).toBeGreaterThan(history!.y+history!.height);expect(live!.y).toBeLessThan(history!.y)}else{expect(facts!.y).toBeGreaterThan(history!.y+history!.height);expect(history!.y).toBeGreaterThan(live!.y+live!.height)}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await expect(page.getByRole('button',{name:'刷新历史',exact:true})).toBeVisible()
 }
 await page.getByRole('button',{name:'资源',exact:true}).click()
 await expect(page).not.toHaveURL(/#latency/)
 await page.reload()
 await expect(page.locator('.detail-resource-charts')).toBeVisible()
 await expect(page.getByRole('region',{name:'网络与流量'})).toContainText('每月 1 日')
 await page.getByRole('button',{name:'网络延迟',exact:true}).click()
 await expect(page).toHaveURL(/#latency$/)
})
test('missing home route stays empty while offline detail keeps durable facts and fits long names',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('monitor-next',JSON.stringify({designVersion:1,probe:'99'})))
 const node={...nodes()[0],online:false,name:'Very long node name '.repeat(12),cpu_name:'Long CPU description '.repeat(15)}
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:[node]}}))
 await page.goto('/node/1#latency')
 await expect(page.locator('.detail-chart-frame')).toContainText('无该线路记录')
 await expect(page.locator('.overview-unavailable')).toContainText('离线')
 await expect(page.locator('.detail-resources,.detail-connections')).toHaveCount(0)
 await expect(page.locator('.overview-account')).toBeVisible()
 for(const width of [320,390]) {
  await page.setViewportSize({width,height:900})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 }
 await page.setViewportSize({width:1440,height:1000})
 const route=page.locator('.latency-route-controls').getByLabel('查看线路',{exact:true})
 await expect(route).toBeVisible();await expect(page.locator('.route-chips')).toHaveCount(0)
 await expect(page.locator('.probe-bulk-actions,.route-search,.probe-solo,.probe-restore')).toHaveCount(0)
 await chooseOption(route,'1')
 await expect(page.locator('.detail-chart-frame .recharts-wrapper')).toBeVisible()
})
