import {chooseOption} from './select'
import {test,expect} from '@playwright/test'
test.use({viewport:{width:390,height:844},hasTouch:true})
test('overview opens map and detail returns to selected region and camera',async({page})=>{
 await page.goto('/?page=overview')
 await page.getByRole('button',{name:'查看地图',exact:true}).click()
 await expect(page).toHaveURL(/page=map/)
 await expect(page.locator('.mm-canvas')).toBeVisible()
 await chooseOption(page.getByRole('combobox',{name:'地图地区',exact:true}),'JP')
 await page.getByRole('group',{name:'世界节点分布地图',exact:true}).focus();await page.keyboard.press('+')
 const camera=await page.locator('.mm-land').getAttribute('transform')
 await page.locator('.mm-node').first().click()
 await expect(page).toHaveURL(/node\//)
 await page.getByRole('button',{name:'返回总览',exact:true}).click()
 await expect(page).toHaveURL(/page=map/)
 await expect(page.getByRole('combobox',{name:'地图地区',exact:true})).toHaveAttribute('data-value','JP')
 await expect(page.locator('.mm-land')).toHaveAttribute('transform',camera!)
 await page.locator('.mm-node').first().click()
 await expect(page).toHaveURL(/node\//)
 await page.goBack()
 await expect(page.locator('.mm-land')).toHaveAttribute('transform',camera!)
 await page.reload()
 await expect(page.getByRole('combobox',{name:'地图地区',exact:true})).toHaveAttribute('data-value','JP')
 await expect(page.locator('.mm-land')).toHaveAttribute('transform',camera!)
})

test('map is lazy, belongs to overview, and respects disabled module',async({page})=>{
 const requests:string[]=[];page.on('request',r=>{if(/MobileMapCanvas-|map-paths-/.test(r.url()))requests.push(r.url())})
 await page.goto('/');await expect(page.locator('#mobile-node-results')).toBeVisible()
 await page.getByRole('button',{name:'概览',exact:true}).click()
 await expect(page.getByRole('button',{name:'查看地图',exact:true})).toBeVisible()
 expect(requests).toHaveLength(0)
 await page.getByRole('button',{name:'查看地图',exact:true}).click()
 await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 expect(requests.length).toBeGreaterThan(0)
 await expect(page.locator('.ma-nav')).toBeHidden()
 await page.goBack();await expect(page).toHaveURL(/page=overview/)
 await page.goForward();await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 await page.route('**/api/themes/hex/config',r=>r.fulfill({json:{module_map:false}}))
 requests.length=0;await page.goto('/?page=map')
 await expect(page.getByText('地图已关闭，可返回概览查看地区分布')).toBeVisible()
 expect(requests).toHaveLength(0)
 await page.getByRole('button',{name:'返回概览',exact:true}).click()
 await expect(page.getByRole('button',{name:'查看地图',exact:true})).toHaveCount(0)
})

test('failed drawing keeps selector and nodes usable and retries',async({page})=>{
 await page.route('**/assets/MobileMapCanvas-*.js',r=>r.abort())
 await page.goto('/?page=map')
 await expect(page.getByRole('button',{name:'重试地图',exact:true})).toBeVisible()
 await chooseOption(page.getByRole('combobox',{name:'地图地区',exact:true}),'JP')
 await expect(page.locator('.mm-node')).toHaveCount(1)
 await page.unroute('**/assets/MobileMapCanvas-*.js')
 await page.getByRole('button',{name:'重试地图',exact:true}).click()
 await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 await expect(page.getByRole('combobox',{name:'地图地区',exact:true})).toHaveAttribute('data-value','JP')
})

test('unknown regions, empty data and late coordinates keep list useful',async({page})=>{
 const {nodes}=await import('../scripts/fixtures.mjs')
 let data=[{...nodes()[0],country:''}]
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:data}}))
 await page.goto('/?page=map')
 await expect(page.getByText('暂无可定位的地区信息，仍可在下方查看节点')).toBeVisible()
 const select=page.getByRole('combobox',{name:'地图地区',exact:true})
 await chooseOption(select,'unknown');await expect(page.locator('.mm-node')).toHaveCount(1)
 data=[{...nodes()[0],country:'JP'}]
 await expect(page.locator('.mm-marker[data-region=JP]')).toBeVisible({timeout:10000})
 await expect(select).toHaveAttribute('data-value','unknown');await expect(page.getByText('该地区暂无节点')).toBeVisible()
 await chooseOption(select,'all');await expect(page.locator('.mm-node')).toHaveCount(1)
 const camera=await page.locator('.mm-land').getAttribute('transform')
 data=[{...nodes()[0],country:'DE'}]
 await expect(page.locator('.mm-node')).toContainText('德国',{timeout:10000})
 await expect(page.locator('.mm-land')).toHaveAttribute('transform',camera!)
 data=[];await expect(page.getByText('还没有节点',{exact:true})).toBeVisible({timeout:10000})
})

for(const width of [320,390,430])test(`phone layout and controls at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});await page.goto('/?page=map')
 await expect(page.locator('.mm-marker').first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 for(const el of await page.locator('.mm-tools button,.mm-marker').all()){
  const box=(await el.boundingBox())!;expect(box.width).toBeGreaterThanOrEqual(43.9);expect(box.height).toBeGreaterThanOrEqual(43.9)
 }
 const select=page.getByRole('combobox',{name:'地图地区',exact:true})
 const marker=page.locator('.mm-marker[data-region=US]'),code='US'
 for(const code of ['DE','GB']){await chooseOption(select,code);await expect(page.locator('.mm-node')).toHaveCount(1)}
 await chooseOption(select,'all')
 await page.getByRole('button',{name:'收起节点列表',exact:true}).click()
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 await marker.tap();await expect(select).toHaveAttribute('data-value',code!)
 await marker.focus();await page.keyboard.press('Enter');await expect(select).toHaveAttribute('data-value','all')
 await page.evaluate(()=>document.documentElement.classList.add('dark'))
 await expect(marker).toBeVisible()
})

test('touch pan and pinch do not select a region; world button restores world',async({page,context})=>{
 await page.goto('/?page=map');await expect(page.locator('.mm-marker').first()).toBeVisible()
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 const land=page.locator('.mm-land'),initial=await land.getAttribute('transform')
 const client=await context.newCDPSession(page)
 const box=(await page.locator('.mm-canvas').boundingBox())!
 const x=box.x+box.width/2,y=box.y+box.height/2
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+40,y:y+20,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
 await expect(land).not.toHaveAttribute('transform',initial!)
 const panned=await land.getAttribute('transform')
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-30,y,id:1},{x:x+30,y,id:2}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-65,y,id:1},{x:x+65,y,id:2}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
 await expect(land).not.toHaveAttribute('transform',panned!)
 await expect(page.getByRole('combobox',{name:'地图地区',exact:true})).toHaveAttribute('data-value','all')
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 await expect(land).toHaveAttribute('transform',initial!)
 await page.setViewportSize({width:390,height:600})
 await page.getByRole('button',{name:'展开节点列表',exact:true}).click()
 await page.locator('.mm-node').last().scrollIntoViewIfNeeded()
 expect(await page.locator('.mm-sheet-content').evaluate(el=>el.scrollTop)).toBeGreaterThan(0)
 expect(await page.evaluate(()=>scrollY)).toBe(0)
})

test('pending node data does not falsely show empty map',async({page})=>{
 let finish!:()=>void;const pending=new Promise<void>(r=>finish=r)
 await page.route('**/api/nodes',async r=>{await pending;await r.continue()})
 await page.goto('/?page=map')
 await page.getByRole('button',{name:'展开节点列表',exact:true}).click()
 await expect(page.getByText('等待节点数据',{exact:true})).toBeVisible()
 await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 await expect(page.locator('.mm-map-message')).toHaveCount(0)
 finish();await expect(page.locator('.mm-node').first()).toBeVisible()
})

test('drag starting on a marker keeps capture after marker leaves the viewport',async({page,context})=>{
 const {nodes}=await import('../scripts/fixtures.mjs')
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:[{...nodes()[0],country:'JP'}]}}))
 await page.goto('/?page=map')
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 const marker=page.locator('.mm-marker'),land=page.locator('.mm-land')
 await expect(marker).toBeVisible()
 const box=(await marker.boundingBox())!,x=box.x+box.width/2,y=box.y+box.height/2
 const client=await context.newCDPSession(page)
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:380,y,id:1}]})
 await expect(marker).toHaveCount(0)
 const midway=await land.getAttribute('transform')
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:385,y,id:1}]})
 await expect(land).not.toHaveAttribute('transform',midway!)
 await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]})
 await expect(page.getByRole('combobox',{name:'地图地区',exact:true})).toHaveAttribute('data-value','all')
})

test('map selection preserves node search and overview scroll; short landscape fits',async({page})=>{
 await page.goto('/')
 await page.getByRole('searchbox',{name:'搜索节点',exact:true}).fill('Tokyo')
 await page.locator('.ma-nav').getByRole('button',{name:'概览',exact:true}).click()
 const entry=page.getByRole('button',{name:'查看地图',exact:true})
 await entry.scrollIntoViewIfNeeded()
 const before=await page.evaluate(()=>scrollY)
 await entry.click()
 await chooseOption(page.getByRole('combobox',{name:'地图地区',exact:true}),'US')
 await page.getByRole('button',{name:'返回概览',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>scrollY)).toBeCloseTo(before,0)
 await page.locator('.ma-nav').getByRole('button',{name:'节点',exact:true}).click()
 await expect(page.getByRole('searchbox',{name:'搜索节点',exact:true})).toHaveValue('Tokyo')
 await expect(page.locator('.ma-node')).toHaveCount(1)
 await page.setViewportSize({width:667,height:375});await page.goto('/?page=map')
 await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 expect((await page.locator('.mm-canvas').boundingBox())!.height).toBe(375)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})


test('slow drawing keeps the list usable and does not reset selected region',async({page})=>{
 let finish!:()=>void;const pending=new Promise<void>(r=>finish=r)
 await page.route('**/assets/MobileMapCanvas-*.js',async r=>{await pending;await r.continue()})
 await page.goto('/?page=map')
 await expect(page.getByText('地图加载中…',{exact:true})).toBeVisible()
 const select=page.getByRole('combobox',{name:'地图地区',exact:true})
 await chooseOption(select,'JP');await expect(page.locator('.mm-node')).toHaveCount(1)
 finish();await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 await expect(select).toHaveAttribute('data-value','JP')
 await page.getByRole('group',{name:'世界节点分布地图',exact:true}).focus();await page.keyboard.press('+')
 const camera=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('hex-mobile-map-v1')!).camera)
 await page.setViewportSize({width:1440,height:900});await expect(page.locator('.region-atlas')).toBeVisible()
 await page.setViewportSize({width:390,height:844});await expect(select).toHaveAttribute('data-value','JP')
 await expect.poll(()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('hex-mobile-map-v1')!).camera)).toEqual(camera)
})


test('first entry from a scrolled overview starts at the map heading',async({page})=>{
 await page.goto('/?page=overview')
 const entry=page.getByRole('button',{name:'查看地图',exact:true})
 await entry.evaluate(el=>el.scrollIntoView({block:'center'}))
 expect(await page.evaluate(()=>scrollY)).toBeGreaterThan(100)
 await entry.click()
 await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 await expect.poll(()=>page.evaluate(()=>scrollY)).toBe(0)
})

test('saved map camera stays stable when node data changes',async({page})=>{
 const {nodes}=await import('../scripts/fixtures.mjs')
 let data=nodes()
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:data}}))
 await page.goto('/?page=map');await expect(page.locator('.mm-marker').first()).toBeVisible()
 const initial=await page.locator('.mm-land').getAttribute('transform')
 data=[{...nodes()[0],country:'JP'}]
 await page.reload();await expect(page.locator('.mm-marker')).toHaveCount(1)
 await expect(page.locator('.mm-land')).toHaveAttribute('transform',initial!)
 await expect(page.locator('.mm-page-header')).toBeVisible()
 await expect(page.locator('.ma-header')).toHaveCount(0)
 await expect(page.locator('.mm-results-heading')).toContainText('1 / 1 在线')
})

test('immersive map starts collapsed and exposes nodes without page scrolling',async({page})=>{
 await page.goto('/?page=map')
 await expect(page.locator('.mm-canvas > svg')).toBeVisible()
 await expect(page.locator('.ma-nav')).toBeHidden()
 const box=(await page.locator('.mm-canvas').boundingBox())!
 expect(box.x).toBe(0);expect(box.y).toBe(0);expect(box.height).toBe(844)
 await expect(page.locator('.mm-sheet')).toHaveAttribute('data-state','collapsed')
 await expect(page.locator('.mm-node').first()).toBeHidden()
 await page.getByRole('button',{name:'展开节点列表',exact:true}).click()
 await expect(page.locator('.mm-node').first()).toBeVisible()
 await page.getByRole('button',{name:'收起节点列表',exact:true}).click()
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 await page.locator('.mm-marker[data-region=US]').tap()
 await expect(page.locator('.mm-sheet')).toHaveAttribute('data-state','half')
 await expect(page.locator('.mm-node').first()).toBeVisible()
 expect(await page.evaluate(()=>scrollY)).toBe(0)
 await page.getByRole('button',{name:'返回概览',exact:true}).click()
 await expect(page.locator('.ma-nav')).toBeVisible()
})

test('sheet handle supports touch and keyboard while list scroll leaves camera still',async({page,context})=>{
 await page.goto('/?page=map');await expect(page.locator('.mm-marker').first()).toBeVisible()
 const toggle=page.getByRole('button',{name:'展开节点列表',exact:true})
 const toggleBox=(await toggle.boundingBox())!
 expect(toggleBox.y+toggleBox.height).toBeLessThanOrEqual(844)
 const handle=page.getByRole('button',{name:'调整列表高度',exact:true})
 const b=(await handle.boundingBox())!,x=b.x+b.width/2,y=b.y+b.height/2
 const client=await context.newCDPSession(page)
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-100,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
 await expect(page.locator('.mm-sheet')).toHaveAttribute('data-state','half')
 await handle.focus();await page.keyboard.press('Enter')
 await expect(page.locator('.mm-sheet')).toHaveAttribute('data-state','expanded')
 await page.setViewportSize({width:390,height:600})
 const camera=await page.locator('.mm-land').getAttribute('transform')
 await page.locator('.mm-node').last().scrollIntoViewIfNeeded()
 await expect(page.locator('.mm-land')).toHaveAttribute('transform',camera!)
 expect(await page.evaluate(()=>scrollY)).toBe(0)
 await handle.press('Enter')
 await expect(page.locator('.mm-sheet')).toHaveAttribute('data-state','half')
 const down=(await handle.boundingBox())!,dx=down.x+down.width/2,dy=down.y+down.height/2
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:dx,y:dy,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:dx,y:dy+90,id:1}]})
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
 await expect(page.locator('.mm-sheet')).toHaveAttribute('data-state','collapsed')
})

test('approved visual uses a close default, floating summary and recoverable world view',async({page})=>{
 await page.goto('/?page=map')
 await expect(page.locator('.mm-marker').first()).toBeVisible()
 const camera=()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('hex-mobile-map-v1')!).camera)
 await expect.poll(async()=>Number((await camera())?.k??0)).toBeGreaterThan(2)
 await expect(page.locator('.mm-region-label').first()).toBeVisible()
 const panel=(await page.locator('.mm-sheet').boundingBox())!
 expect(panel.x).toBeGreaterThanOrEqual(15)
 expect(panel.width).toBeLessThan(390)
 expect(panel.y+panel.height).toBeLessThan(834)
 expect(panel.height).toBeLessThanOrEqual(82)
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 await expect.poll(async()=>Number((await camera()).k)).toBeLessThanOrEqual(.94)
 await expect(page.locator('.mm-marker[data-region=US]')).toBeVisible()
 const svg=page.getByRole('group',{name:'世界节点分布地图',exact:true})
 await svg.focus();await page.keyboard.press('+')
 await expect.poll(async()=>Number((await camera()).k)).toBeGreaterThan(.94)
 await page.keyboard.press('Home')
 await expect.poll(async()=>Number((await camera()).k)).toBeLessThanOrEqual(.94)
})


test('region selection settles with motion and world view interrupts it',async({page})=>{
 await page.emulateMedia({reducedMotion:'no-preference'})
 await page.goto('/?page=map');await expect(page.locator('.mm-region-label').first()).toBeVisible()
 await chooseOption(page.getByRole('combobox',{name:'地图地区',exact:true}),'US')
 await expect.poll(()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('hex-mobile-map-v1')!).camera.x)).toBe(259)
 const marker=(await page.locator('.mm-marker[data-region=US]').boundingBox())!
 const sheet=(await page.locator('.mm-sheet').boundingBox())!
 expect(marker.y+marker.height).toBeLessThan(sheet.y)
 await chooseOption(page.getByRole('combobox',{name:'地图地区',exact:true}),'JP')
 await page.getByRole('button',{name:'查看全球',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('hex-mobile-map-v1')!).camera.x)).toBe(500)
 await page.waitForTimeout(350)
 expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('hex-mobile-map-v1')!).camera.x)).toBe(500)
})
