// Desktop composition coverage; phone workflows live in mobile-app/refinement/charts-refined and ux-* suites.
import {test,expect} from '@playwright/test'
import {nodes} from '../scripts/fixtures.mjs'
test('table traffic follows accounting mode, follows independent network columns and hides persistently',async({page})=>{
 await page.addInitScript(()=>{if(!sessionStorage.getItem('monitor-next-browse-v1'))sessionStorage.setItem('monitor-next-browse-v1',JSON.stringify({view:'table',columns:['cpu','memory','disk','upload','download','latency','expiry']}))})
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:['up','down','max','sum'].map((traffic_mode,i)=>({...nodes()[0],id:i+1,name:traffic_mode,traffic_mode,traffic_limit:i===3?0:1024**4}))}}))
 await page.goto('/')
 await expect(page.getByRole('button',{name:'流量用量 / 总额度',exact:true})).toBeVisible()
 const headers=await page.locator('thead th').evaluateAll(els=>els.map(el=>el.getAttribute('data-column')))
 expect(headers.slice(headers.indexOf('download'),headers.indexOf('traffic')+1)).toEqual(['download','latency','loss','probe','traffic'])
 await expect(page.locator('.table-traffic')).toHaveText(['12.0 GB / 1.00 TB','42.0 GB / 1.00 TB','42.0 GB / 1.00 TB','54.0 GB / ∞'])
 await expect(page.locator('.table-ping').getByRole('button',{name:'刷新延迟数据'})).toHaveCount(0)
 await expect(page.locator('.table-ping').getByRole('button',{name:'历史曲线'})).toHaveCount(0)
 await page.getByRole('button',{name:'流量用量 / 总额度',exact:true}).click()
 await expect(page.locator('.table-node-name').first()).toContainText('up')
 await page.getByRole('button',{name:'流量用量 / 总额度 ↑',exact:true}).click()
 await expect(page.locator('.table-node-name').first()).toContainText('sum')
 await page.locator('.table-scroll').screenshot({path:'tests/artifacts/table.png'})
 await page.evaluate(()=>{const key='monitor-next-browse-v1',saved=JSON.parse(sessionStorage.getItem(key)!);sessionStorage.setItem(key,JSON.stringify({...saved,columns:saved.columns.filter((key:string)=>key!=='traffic')}))});await page.reload()
 await expect(page.locator('.table-traffic')).toHaveCount(0)
})

test('expiry countdown includes normal, imminent, today, expired and missing dates',async({page})=>{
 await page.clock.install({time:new Date('2026-09-20T12:00:00')})
 await page.addInitScript(()=>sessionStorage.setItem('monitor-next-browse-v1',JSON.stringify({view:'table'})))
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:['2026-10-20','2026-09-22','2026-09-20','2026-09-19',null].map((expires_at,i)=>({...nodes()[0],id:i+1,name:`Node ${i+1}`,expires_at}))}}))
 await page.goto('/')
 await expect(page.locator('.table-expiry strong')).toHaveText(['30 天后到期','2 天后到期','今天到期','已过期 1 天','未设到期'])
 await expect(page.locator('.table-expiry[data-state=soon]')).toHaveCount(2)
 await expect(page.locator('.table-expiry[data-state=expired]')).toHaveCount(1)
 await page.locator('.table-ping strong').first().waitFor()
 await page.locator('.table-scroll').screenshot({path:'tests/artifacts/table-countdown.png'})
 await page.clock.fastForward(86400000)
 await expect(page.locator('.table-expiry strong').first()).toHaveText('29 天后到期')
})
