import type {ResourceMetricKey} from './ResourceHistory'
import type {Node} from '@/lib/api'
import {liveMetrics,nodeState} from '@/lib/freshness'
import {adaptiveRateParts,bytes,percent,money,CYCLES,daysUntil,relativeTime} from '@/lib/format'
import {trafficUsage,trafficPeriodLabel} from '@/lib/traffic'
import {tr,locale} from '@/lib/i18n'
import {ChevronRight} from 'lucide-react'
import {useState} from 'react'
export function MobileDetailOverview({node,totals,onNetwork,onResource}:{node:Node;totals:boolean;onNetwork:()=>void;onResource:(metric:ResourceMetricKey)=>void}){
 const [billingOpen,setBillingOpen]=useState(false)
 const m=liveMetrics(node),traffic=trafficUsage(node),days=daysUntil(node.expires_at)
 const upload=adaptiveRateParts(m?.net_tx??NaN),download=adaptiveRateParts(m?.net_rx??NaN)
 return <div className="ma-detail-overview">
  {m?<><section className="ma-panel"><h2>{tr('资源使用')}</h2><div className="ma-big-grid">{([
   {key:'cpu',label:'CPU',value:m.cpu.toFixed(1),percent:m.cpu,foot:tr('{0} 核',node.cpu_cores),capacity:false,action:tr('查看 CPU 历史趋势')},
   {key:'mem_used',label:tr('内存'),value:percent(m.mem_used,m.mem_total).toFixed(1),percent:percent(m.mem_used,m.mem_total),foot:`${bytes(m.mem_used)} / ${bytes(m.mem_total)}`,capacity:true,action:tr('查看内存历史趋势')},
   {key:'disk_used',label:tr('硬盘'),value:percent(m.disk_used,m.disk_total).toFixed(1),percent:percent(m.disk_used,m.disk_total),foot:`${bytes(m.disk_used)} / ${bytes(m.disk_total)}`,capacity:true,action:tr('查看硬盘历史趋势')},
   {key:'load',label:tr('负载'),value:m.load[0].toFixed(2),percent:null,foot:tr('1 分钟 · {0} 核',node.cpu_cores),capacity:false,action:undefined}
  ] as const).map(metric=>{const Tag=metric.key==='load'?'div':'button';return <Tag className={`ma-big-metric${metric.action?' ma-metric-action':''}`} data-kind={metric.key} key={metric.key} aria-label={metric.action} aria-describedby={metric.action?`ma-${metric.key}-value${!metric.capacity||totals?` ma-${metric.key}-capacity`:''}`:undefined} onClick={metric.key==='load'?undefined:()=>onResource(metric.key as ResourceMetricKey)}><small className="ma-metric-label">{metric.label}{metric.action&&<ChevronRight size={14} aria-hidden="true"/>}</small><strong id={`ma-${metric.key}-value`}>{metric.value}<small>{metric.percent!==null?' %':''}</small></strong>{metric.percent!==null&&<div className="ma-track" data-hot={metric.percent>=85}><i style={{width:`${Math.min(100,Math.max(0,metric.percent))}%`}}/></div>}{(!metric.capacity||totals)&&<p id={`ma-${metric.key}-capacity`}>{metric.foot}</p>}</Tag>})}</div></section><section className="ma-panel"><h2>{tr('实时网速')}</h2><div className="ma-big-grid"><button className="ma-big-metric ma-metric-action" data-kind="upload" aria-label={tr('查看上行网速历史')} aria-describedby="ma-upload-value" onClick={()=>onResource('network')}><small className="ma-metric-label">↑ {tr('上行')}<ChevronRight size={14} aria-hidden="true"/></small><strong id="ma-upload-value">{upload.amount} <small>{upload.unit}</small></strong></button><button className="ma-big-metric ma-metric-action" data-kind="download" aria-label={tr('查看下行网速历史')} aria-describedby="ma-download-value" onClick={()=>onResource('network')}><small className="ma-metric-label">↓ {tr('下行')}<ChevronRight size={14} aria-hidden="true"/></small><strong id="ma-download-value">{download.amount} <small>{download.unit}</small></strong></button></div><button className="ma-row" onClick={onNetwork}><span>{tr('网络质量')}</span><ChevronRight size={16}/></button></section></>:<section className="ma-panel"><h2>{nodeState(node)==='offline'?tr('离线'):nodeState(node)==='stale'?tr('数据已过期'):tr('等待首次上报')}</h2><p className="ma-muted">{tr('最近上报时间')}<br/>{node.last_seen>0?<time dateTime={new Date(node.last_seen*1000).toISOString()} title={new Date(node.last_seen*1000).toLocaleString(locale())}>{relativeTime(node.last_seen)} · {new Date(node.last_seen*1000).toLocaleString(locale())}</time>:tr('上次上报时间未知')}</p><button className="ma-row" onClick={onNetwork}><span>{tr('查看网络历史')}</span><ChevronRight size={16}/></button></section>}
  <section className="ma-panel ma-billing-panel"><button type="button" className="ma-billing-toggle" aria-expanded={billingOpen} aria-controls="ma-billing-details" onClick={()=>setBillingOpen(value=>!value)}><span>{tr('流量与账单')}<small>{bytes(traffic.value)} / {node.traffic_limit>0?bytes(node.traffic_limit):tr('不限量')}{days!==null&&days<=7&&<em className="ma-warning"> · {days<0?tr('已到期'):days===0?tr('今日到期'):tr('剩余 {0} 天',days)}</em>}</small></span><ChevronRight size={17} aria-hidden="true"/></button><div id="ma-billing-details" hidden={!billingOpen}><div className="ma-row"><span>{tr(trafficPeriodLabel(node))}</span><small>{bytes(traffic.value)} / {node.traffic_limit>0?bytes(node.traffic_limit):tr('不限量')}</small></div>{node.traffic_limit>0&&<div className="ma-track" data-hot={traffic.value>=node.traffic_limit}><i style={{width:`${Math.min(100,traffic.value/node.traffic_limit*100)}%`}}/></div>}<div className="ma-row"><span>{tr('费用')}</span><small>{node.price>0?`${money(node.price,node.currency)} / ${tr(CYCLES[node.billing_cycle]??node.billing_cycle)}`:'—'}</small></div><div className="ma-row"><span>{tr('到期时间')}</span><small>{node.expires_at??tr('未设到期')}{days!==null&&days<=7&&<span className="ma-warning">{days<0?tr('已到期'):days===0?tr('今日到期'):tr('剩余 {0} 天',days)}</span>}</small></div></div></section>
 </div>
}
